// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsNfkixejWKPZ1Ub50Sg6HuqzIb_bM0ak',
    appId: '1:662823526299:web:d8bf961ad1f92978738b3e',
    messagingSenderId: '662823526299',
    projectId: 'cryptoduse-e7d87',
    authDomain: 'cryptoduse-e7d87.firebaseapp.com',
    storageBucket: 'cryptoduse-e7d87.firebasestorage.app',
    measurementId: 'G-PMLK1C1YZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN_qZSoiN-LNZIcW-z8H8jy7xFX_NYrgk',
    appId: '1:662823526299:android:a89f5d87be1820fa738b3e',
    messagingSenderId: '662823526299',
    projectId: 'cryptoduse-e7d87',
    storageBucket: 'cryptoduse-e7d87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3yZ1DVcQuE7Yrb7APjtG2s5GBJ2fHrA8',
    appId: '1:662823526299:ios:6047fb7bd50639fb738b3e',
    messagingSenderId: '662823526299',
    projectId: 'cryptoduse-e7d87',
    storageBucket: 'cryptoduse-e7d87.firebasestorage.app',
    androidClientId: '662823526299-h3pagt80l0ufteguaea4pha3qokkfc22.apps.googleusercontent.com',
    iosClientId: '662823526299-bli3j284u1htaa6lvn8vacmhj7h8f59v.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoInsight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3yZ1DVcQuE7Yrb7APjtG2s5GBJ2fHrA8',
    appId: '1:662823526299:ios:6047fb7bd50639fb738b3e',
    messagingSenderId: '662823526299',
    projectId: 'cryptoduse-e7d87',
    storageBucket: 'cryptoduse-e7d87.firebasestorage.app',
    androidClientId: '662823526299-h3pagt80l0ufteguaea4pha3qokkfc22.apps.googleusercontent.com',
    iosClientId: '662823526299-bli3j284u1htaa6lvn8vacmhj7h8f59v.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoInsight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsNfkixejWKPZ1Ub50Sg6HuqzIb_bM0ak',
    appId: '1:662823526299:web:640d0266515af35d738b3e',
    messagingSenderId: '662823526299',
    projectId: 'cryptoduse-e7d87',
    authDomain: 'cryptoduse-e7d87.firebaseapp.com',
    storageBucket: 'cryptoduse-e7d87.firebasestorage.app',
    measurementId: 'G-2HT2CHEM1Y',
  );

}